### ISSUE TITLE
Sparse 0.3.1 getting installed with numpy 2.1.1

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/sparse-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

i think numba limits newer versions of sparse being installed with the command

```
mamba create --name sparse sparse "numpy>=2.1.1" --channel conda-forge --override-channels --yes
conda run -n sparse python -c "import sparse"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/miniforge3/envs/sparse/lib/python3.12/site-packages/sparse/__init__.py", line 1, in <module>
    from .coo import COO, elemwise, tensordot, concatenate, stack, dot, triu, tril, where, \
  File "/home/mark/miniforge3/envs/sparse/lib/python3.12/site-packages/sparse/coo.py", line 4, in <module>
    from collections import Iterable, defaultdict, deque
ImportError: cannot import name 'Iterable' from 'collections' (/home/mark/miniforge3/envs/sparse/lib/python3.12/collections/__init__.py)
```

xref: https://github.com/pydata/xarray/pull/9540

unclear what the right path is....

### Installed packages

```shell
# packages in environment at /home/mark/miniforge3/envs/sparse:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_0    conda-forge
libblas                   3.9.0           24_linux64_openblas    conda-forge
libcblas                  3.9.0           24_linux64_openblas    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgfortran               14.1.0               h69a702a_1    conda-forge
libgfortran-ng            14.1.0               h69a702a_1    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
liblapack                 3.9.0           24_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
numpy                     2.1.1           py312h58c1407_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
python                    3.12.6          hc5c86c4_1_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.14.1          py312h7d485d2_0    conda-forge
setuptools                74.1.2             pyhd8ed1ab_0    conda-forge
sparse                    0.3.1                      py_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/mark/.condarc
 populated config files : /home/mark/miniforge3/.condarc
                          /home/mark/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.7.1=0
                          __glibc=2.39=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /home/mark/miniforge3  (writable)
      conda av data dir : /home/mark/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/ramona_ml/linux-64
                          https://conda.anaconda.org/ramona_ml/noarch
                          https://conda.anaconda.org/mark.harfouche/linux-64
                          https://conda.anaconda.org/mark.harfouche/noarch
                          https://conda.anaconda.org/t/<TOKEN>/ramonaoptics/linux-64
                          https://conda.anaconda.org/t/<TOKEN>/ramonaoptics/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mark/miniforge3/pkgs
                          /home/mark/.conda/pkgs
       envs directories : /home/mark/miniforge3/envs
                          /home/mark/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.5 Linux/6.8.0-45-generic ubuntu/24.04.1 glibc/2.39 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by hameerabbasi** [comment]
Could you try installing `numba` with the same NumPy version? We never pinned at `<2.1`, but IIRC Numba does. 0.3.1 was perhaps the last version to not use Numba.

**Comment by hmaarrfk** [comment]
This is my thought too. I just stepped away from my keyboard. 

Maybe we should just limit python 3.12 compatibility

**Comment by hameerabbasi** [comment]
> Maybe we should just limit python 3.12 compatibility

Is this issue Python 3.12-specific? I'd be surprised if that was true.

**Comment by hmaarrfk** [comment]
This also happens with python 3.10.

**Comment by hmaarrfk** [comment]
I think we likely need to patch version 0.3.1 from 6 years ago to limit its compatibility with "3.9" at the most.

https://github.com/conda-forge/sparse-feedstock/commit/9d2cd1adbb8eb0fa5bc5d1d6768660c0c5e62251#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR15

**Comment by hameerabbasi** [comment]
Why not limit the actual problem at hand and limit 0.3.1 to NumPy 1.x, as it probably won't support 2.x anyway?

I'd be happy to accept a PR, but I'm not entirely sure how old releases are patched.

**Comment by hameerabbasi** [comment]
`sparse` 0.3.1 build 1 with updated deps is up on `conda-forge`: https://anaconda.org/conda-forge/sparse/files?version=0.3.1
